---
title: "Descriptive Analysis v0.2"
author: "Benjamin T. Carter, PhD"
date: "Generated: `r Sys.time()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
params:
  respVar: "return_in_14"
  d.frame: "did you forget me?"
---

```{r}
# packages

library(dplyr)
library(tidyr)
library(lubridate)
library(compareGroups)

# data
d.frame <- params$d.frame
respVar <- params$respVar

# variable lists
# identify variable types and make lists
numeric.vars <- unlist(lapply(d.frame, is.numeric))
boolean.vars <- unlist(lapply(d.frame, is.logical))
categorical.vars <- unlist(lapply(d.frame, is.character))
categorical.vars <- union(categorical.vars,
                          unlist(lapply(d.frame, is.factor)))

```

### Table 1

```{r}

if (is.logical(d.frame[[respVar]])) {
  d.frame[[respVar]] <- as.factor(d.frame[[respVar]])
}

thing <- paste(respVar, "~", " .", sep = "")

comp.obj <- compareGroups(
  thing,
  d.frame,
  max.xlev = 22
)

cap <- paste("Descriptive table for ", respVar, ".", sep = "")

createTable(comp.obj, show.all = TRUE, show.p.overall = TRUE) %>% export2md(caption = cap)

```

## Univariate analyses for `r respVar`

### Categorical factors

```{r}

cat_vars <- c("Fed_Ethnicity",
              "Language",
              "Race",
              "Marital_Status",
              "Sex",
              "Religion_binary",
              "Building",
              "ZipCode",
              "FIPS",
              "RUCC_2013",
              "topic",
              "chapter")

CatChi <- data.frame(
  variable = as.character(),
  Xsq = as.numeric(),
  df = as.numeric(),
  p = as.numeric(),
  row.names = NULL
)

CatChiList <- list()

for (cat in cat_vars){
  res <- chisq.test(
    d.frame[[cat]],
    d.frame[[respVar]]
  )
  
  if (res$p.value < 0.05){
    res.df <- data.frame(
      variable = cat,
      Xsq = res$statistic,
      df = res$parameter,
      p = res$p.value,
      row.names = NULL
    )
    
    CatChi <- rbind(CatChi, res.df)
    
    CatChiList[[cat]] <- res
    
    residuals <- data.frame(res$residuals) %>% 
      rename(
        Residual = Freq
      )
    
    Zscores <- data.frame(100*res$residuals^2/res$statistic) %>% 
      rename(
        Z = Freq
      ) %>% 
      mutate(
        Significant = if_else(
          abs(Z) > 1.96,
          TRUE,
          FALSE
        )
      )
    
    residuals <- residuals %>% 
      left_join(Zscores)
    
    CatChiList[[paste(cat,"_plot", sep = "")]] <- residuals %>% 
      ggplot(
        aes(
          d.frame..cat..,
          d.frame..respVar..,
          size = Z,
          shape = Significant,
          color = Residual
        )
      ) +
      geom_point(alpha = 0.7) +
      theme_classic() +
      scale_color_gradient2(low = "#0000ff", mid = "#008000", high = "#ff0000") +
      labs(
        title = paste(cat, "Significance Plot"),
        y = respVar,
        x = cat,
        size = "St. Residual",
        shape = "Significance, p < 0.05"
      ) + 
      theme(
        axis.text.x = element_text(angle = 90)
      )

  }

}

print(CatChiList)

```

### Continuous Variables

```{r}
col.df <- data.frame(name = colnames(d.frame))
col.df$class <- apply(col.df, 1, function(x) class(d.frame[[x]]))

col.continuous <- col.df %>% 
  filter(
    class == 'numeric'
  ) %>% 
  mutate(
    class = unlist(class)
  ) %>% 
  filter(
    !(name %in% c("PersonID",
                  "EncounterID",
                  "DiagnosisPrioritySEQ",
                  "id",
                  "days_to_return"))
  )

continuous.list <- list()

for (var in col.continuous$name){
  mods <- glm(d.frame[[respVar]]~d.frame[[var]],
               d.frame,
               family = "binomial")
  
  summ <- summary(mods)
  p<- as.data.frame(summ$coefficients)
  p <- p[2,4]
  
  if (p<=0.05){
    continuous.list[[var]]<-summ
    continuous.list[[paste(var,"_plot",sep = "")]] <- ggplot(d.frame,
                                                             aes(.data[[var]],
                                                                 .data[[respVar]])) +
      geom_jitter() +
      theme_classic() +
      labs(
        x = var
      ) +
      scale_x_log10()
  }
}

print(continuous.list)

```

### Priority ICD-10 Codes

```{r}
## most common Priority ICD10
df.icd.counts <- d.frame %>% 
  group_by(ICD_code, .data[[respVar]]) %>% 
  summarise(
    n = n()
  ) %>% 
  ungroup() %>% 
  arrange(
    desc(.data[[respVar]]),
    desc(n)
  ) %>% 
  pivot_wider(
    names_from = .data[[respVar]],
    values_from = n,
    values_fill = 0
  ) %>% 
  mutate(
    ratio = `TRUE`/`FALSE`,
    percentage = `TRUE`/(`FALSE` + `TRUE`)
  ) %>% 
  arrange(
    desc(percentage),
    desc(`TRUE`)
  )

## priority ICD-10 with most significant association with readmission
df.chi <- d.frame %>% 
  mutate(
    n = 1
  ) %>% 
  pivot_wider(
    names_from = ICD_code,
    values_from = n,
    values_fill = 0
  )

df.chi.results <- data.frame(ICD = as.character(),
                             Chi2 = as.numeric(),
                             p = as.numeric())

for (i in seq(59, length(colnames(df.chi)))){
  chiTest <- chisq.test(
    df.chi[[respVar]],
    df.chi[[i]]
  )
  
  a <- colnames(df.chi)[i]
  
  res <- data.frame(ICD = a,
                    Chi2 = chiTest$statistic,
                    p = chiTest$p.value)
  
  df.chi.results <- rbind(df.chi.results, res)
}

row.names(df.chi.results) <- NULL

library(icd.data)
ICD <- icd10cm2016 %>% 
  mutate(
    code = as.character(code)
  )

df.icd.sig <- df.icd.counts %>% 
  left_join(
    df.chi.results,
    by = c("ICD_code" = "ICD")
  )

df.icd.counts <- NULL
df.chi.results <- NULL

## top 50 ICD-10 codes
top50 <- df.icd.sig %>%
  arrange(
    desc(Chi2),
    p
  ) %>%
  head(50) %>%
  left_join(
    ICD[c(1,3,6:8)],
    by = c("ICD_code" = "code")
  )

cappy <- paste("This table displays the top 50 priority ICD codes most associated with ", respVar, " values (TRUE or FALSE).", sep = "")

knitr::kable(top50, caption = cappy) %>% kableExtra::kable_styling(bootstrap_options = c("striped","condensed")) %>% kableExtra::scroll_box(width = "100%")

```

### Priority ICD-10 Chapters

```{r fig.height=10}
## most common priority ICD10 chapter
df.icd.counts <- d.frame %>% 
  group_by(chapter, .data[[respVar]]) %>% 
  summarise(
    n = n()
  ) %>% 
  ungroup()


# chi square
res.df <- d.frame %>% 
  select(
    .data[[respVar]], 
    chapter
  ) %>%
  mutate(
    chapter = as.character(chapter)
  ) %>% 
  mutate(
    chapter = if_else(
      is.na(chapter),
      "No affiliated chapter",
      chapter
    )
  ) %>% 
  mutate(
    chapter = as.factor(chapter),
    # .data[[respVar]] = as.factor(.data[[respVar]])
  )

res <- chisq.test(res.df$chapter, res.df[[respVar]])
res

residuals <- data.frame(res$residuals) %>%
  rename(
    Residual = Freq
  )
    
Zscores <- data.frame(100*res$residuals^2/res$statistic) %>% 
  rename(
    Z = Freq
  ) %>% 
  mutate(
    Significant = if_else(
      abs(Z) > 1.96,
      TRUE,
      FALSE
    )
  )
    
residuals <- residuals %>% 
  left_join(Zscores)

residuals %>%
  ggplot(
    aes(
      res.df.chapter,
      res.df..respVar..,
      size = Z,
      shape = Significant,
      color = Residual
    )
  ) +
  geom_point(alpha = 0.7) +
  theme_classic() +
  scale_color_gradient2(low = "#0000ff", mid = "#008000", high = "#ff0000") +
  labs(
    title = paste("Priority ICD Chapter Significance"),
    y = respVar,
    x = "Chapter",
    size = "St. Residual",
    shape = "Significance, p < 0.05"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  )

```

### All ICD-10 Codes

```{r}
resp.vec <- c("EncounterID", respVar) # get response var
resp.vec <- d.frame %>% 
  select(all_of(resp.vec))

icd.vec <- c("EncounterID", "ICD_block_all") # get lists of ICDs
icd.vec <- d.frame %>% # unzip ICD list
  select(all_of(icd.vec)) %>% 
    separate_rows(ICD_block_all, sep = "; ")

ICD <- icd.data::icd10cm2016 %>% # join ICD list with ICD chapter names
  mutate(
    three_digit = as.character(three_digit)
  ) %>% 
  right_join(
    icd.vec,
    by = c("three_digit" = "ICD_block_all")
  ) %>% # join with response variable
  left_join(
    resp.vec,
    by = c("EncounterID")
  ) %>% 
  select(
    EncounterID,
    three_digit,
    chapter,
    params$respVar
  )

res <- chisq.test(ICD$three_digit, ICD[[respVar]])
res

residuals <- data.frame(res$residuals) %>%
  rename(
    Residual = Freq
  )
    
Zscores <- data.frame(100*res$residuals^2/res$statistic) %>% 
  rename(
    Z = Freq
  ) %>% 
  mutate(
    Significant = if_else(
      abs(Z) > 1.96,
      TRUE,
      FALSE
    )
  )
    
icdDf <- icd.data::icd10cm2016 %>% 
  mutate(
    three_digit = as.character(three_digit)
  ) %>% 
  select(
    -code,
    -billable,
    -short_desc,
    -long_desc
  ) %>% 
  unique()

res.tab <- residuals %>% 
  left_join(Zscores) %>% 
  filter(
    Significant == TRUE
  ) %>% 
  mutate(
    ICD.three_digit = as.character(ICD.three_digit)
  ) %>% 
  left_join(
    icdDf,
    by = c("ICD.three_digit" = "three_digit")
  ) %>% 
  select(
    ICD.three_digit,
    major,
    Residual,
    Z,
    Significant
  ) %>% 
  mutate(
    major = as.character(major)
  )

# res.tab$major[res.tab$ICD.code == "K8510"] <- "Biliary acute pancreatitis without necrosis or infection"

knitr::kable(res.tab) %>% kableExtra::kable_styling(bootstrap_options = c("striped","condensed")) %>% kableExtra::scroll_box(width = "100%")

```

### All ICD-10 Chapters
```{r}
res <- chisq.test(ICD$chapter, ICD[[respVar]])
res

residuals <- data.frame(res$residuals) %>%
  rename(
    Residual = Freq
  )
    
Zscores <- data.frame(100*res$residuals^2/res$statistic) %>% 
  rename(
    Z = Freq
  ) %>% 
  mutate(
    Significant = if_else(
      abs(Z) > 1.96,
      TRUE,
      FALSE
    )
  )
    
residuals <- residuals %>% 
  left_join(Zscores)

residuals %>%
  ggplot(
    aes(
      ICD.chapter,
      ICD..respVar..,
      size = Z,
      shape = Significant,
      color = Residual
    )
  ) +
  geom_point(alpha = 0.7) +
  theme_classic() +
  scale_color_gradient2(low = "#0000ff", mid = "#008000", high = "#ff0000") +
  labs(
    title = paste("ICD Chapter Significance"),
    y = respVar,
    x = "Chapter",
    size = "St. Residual",
    shape = "Significance, p < 0.05"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  )

cappy <- paste("ICD-10 chapters with a significant association with ", 
               params$respVar,
               ".",
               sep = "")

knitr::kable(residuals[residuals$Significant == TRUE,], 
             caption = cappy,
             row.names = FALSE) %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped","condensed")) %>% kableExtra::scroll_box(width = "100%")

```

