---
title: "Same Day Care 2.0"
output:
  html_document:
    df_print: paged
    code_folding: hide
---

```{r setup}
# packages ####
library(dplyr)
library(stringr)
library(ggplot2)
library(icd.data)
library(icd)

# paths ####
data.dir.path <- file.path("C:","Users","CarteB","BILLINGS CLINIC", "CSI & David Hedges - Same Day Care Project", "data")
df.path <- file.path(data.dir.path, "sdc.2017-2019.2020-06-29.csv")
out.dir.path <- file.path("C:","Users","CarteB","BILLINGS CLINIC", "CSI & David Hedges - Same Day Care Project", "results")
```

```{r loadData}
# load data ####

cols <- c(
  "DTS",
  "PersonID",
  "EncounterID",
  "AppointmentID",
  "ActiveIndicatorCD",
  "Ethnicity",
  "Language",
  "Race",
  "Marital_Status",
  "Sex",
  "Religion",
  "ZipCode",
  "Location",
  "Facility",
  "AdmitType",
  "EncounterType",
  "ReasonForVisit",
  "DiagnosisFreeTXT",
  "DiagnosisPrioritySEQ",
  "ICD",
  "DiagnosisType",
  "DiagnosisDSC",
  "DiagnosisNormDSC",
  "RespiratoryFailure",
  "CharlsonDeyoScore"
)

df <- read.csv2(
  df.path,
  header = FALSE,
  sep = ",",
  col.names = cols,
  stringsAsFactors = FALSE,
  na.strings = "NULL"
  )

```


```{r preproc}

# correct bad entries ####
df[1,1] <- "2017-01-01 00:00:00.0000000"

df.processed <- df %>% 
  mutate(
    Race = na_if(
      Race,
      "0"
    ),
    Race = na_if(
      Race,
      " "
    ),
    Ethnicity = na_if(
      Ethnicity,
      "0"
    ),
    Ethnicity = na_if(
      Ethnicity,
      " "
    )
  ) %>% 
  mutate(
    Race = replace_na(
      Race,
      "Not Obtained"
    ),
    Ethnicity = replace_na(
      Ethnicity,
      "Not Obtained"
    ),
    ZipCode = gsub(
      "(\\d{5}).*",
      "\\1",
      ZipCode
    ),
    ICD_block = gsub(
      "(\\w\\d{2}).?(.*)",
      "\\1",
      ICD
    ),
    ICD_code = gsub(
      "(\\w\\d{2}).?(.*)",
      "\\1\\2",
      ICD
    )
  ) %>% 
  filter(
    !is.na(ICD_code),
    !grepl(
      "\\.",
      ICD_code
    )
  )

```

# Basic stats for all patient encounters from 2017-2019

Unique PersonIDs: `r length(unique(df$PersonID))`
Unique EncounterIDs: `r length(unique(df$EncounterID))`
Primary Dx: `r nrow()
Unique Zipcodes: `r length(unique(df$ZipCode))`
Unique ICD-10s: `r length(unique(df$ICD))`
Average Charlson-Deyo: `r mean(df$CharlsonDeyoScore, na.rm = TRUE)`


