---
title: "summary"
author: "Benjamin Carter"
date: "11/9/2020"
output: html_document
---

## Potentially enriching data to add.
- Basic vital signs, Rx, preexisting conditions.
- Previous LOS, days since last encounter.
- PCP flag, specialty
- Count for SDC appoitnments in the past year

## Ethical Considerations
- What to do when the model stratifies a patient as high risk? What information do we need to guide a course of action?
- What do we do with false positives? Financial repercussions?
- What do we do with false negatives? Liability?

## Potential other studies/comparisons
- Do respiratory disease trends flip in 2020 due to COVID? (should be a reflection of change in PCP practice)
- Consider comparison against all other primary care visits. E.g. Is there a difference in the number of single individuals accessing care between PCP's and SDC?
- Consider using this as a case study for cleaning up how data is entered.
- Consider doing a PCA to examine latent variables and correlations.
- Maybe targeted interventions for minority populations, e.g. park a mobile clinic on/near a reservation at a regular time each week to facilitate care.
- Examine demographic information on a per capita basis (e.g. returns/neighborhood population).

## Data Issues
- Chronic disease tables are terrible as is. Need to create SAM or something. How to determine? Presence of relevant ICD-10 in the past 5-10 years? Look for prescribed medications?
- Why are some encounterID's '0'?
- Consider regulation of address information and differentiating between mailing and residential address. This important in terms of readiness to track disease outbreaks and public health interventions. E.g. PO Box addresses should be entered as a mailing address not a home address. 'Attn. John Doe' should be entered as the second or third line for street address. Not first.
- What/where is *Same Day Care* Nurse Unit? Why are the number of buildings and Nurse Units different? Shouldn't they be the same? If not, why?
- Is 14 days really the optimal window?
